
build-centos7:
   image: centos:7
   script:
      - yum install -y rpm-build
      - echo "Building RPM"
      - bash pkg/pkg_rpm.sh
   only:
      - tags
   except:
      - branches
   artifacts:
      paths:
         - package/*.rpm
         - /root/rpmbuild/SRPMS/*.rpm
         - /root/rpmbuild/RPMS/noarch/*.rpm

