
build-centos7:
   image: centos:7
   script:
      - echo "Building RPM"
      - pwd
      - ls
      - ls /
   only:
      - tags
   except:
      - branches
   artifacts:
      paths:
         - package/*.rpm


build-ubuntu16:
   image: ubuntu:16.04
   script:
      - echo "Building DPKG"
      - pwd
      - ls
      - ls /
   only:
      - tags
   except:
      - branches
   artifacts:
      paths:
         - package/*.dpkg


