
build-ubuntu16:
   image: ubuntu:16.04
   script:
      - apt-get update
      - apt-get install -y build-essential
      - apt-get install -y curl
      - echo "Building DPKG"
      - cd pkg
      - ./pkg_dpkg.sh
      - pwd
      - ls
   only:
      - tags
   except:
      - branches
   artifacts:
      paths:
         - package/*.deb
         - /*.deb
         - pkg/*.deb

