
build-centos7:
   image: centos:7
   script:
      - yum install -y rpm-build
      - echo "Building RPM"
      - cp pkg/pkg_rpm.sh .
      - ./pkg_rpm.sh
   only:
      - tags
   except:
      - branches
   artifacts:
      paths:
         - package/*.rpm

