
groups:

  - name: sentinel.rules
    rules:

    # sentinel down
    - alert: Sentinel_is_Down
      expr: sentinel_up{} == 0
      for: 1m
      labels:
        severity: critical
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - Sentinel is Down
        description: "{{ $labels.instance }} of job {{ $labels.job }} Sentinel is Down\n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # defunct processes
    - alert: Detect_Defunct_Processes
      expr: sentinel_job_output{defunct!="0",sentinel_job="proc-monitor"}
      for: 1m
      labels:
        severity: warning
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - Defunct_Processes
        description: "{{ $labels.instance }} of job {{ $labels.job }} Defunct_Processes \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # root ssh
    - alert: Detect_Root_SSH
      expr: sentinel_job_output{prog="ssh",user="root",sentinel_job="established-check"}
      for: 0m
      labels:
        severity: info
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - Detect_Root_SSH
        description: "{{ $labels.instance }} of job {{ $labels.job }} Detect_Root_SSH \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # detect file change
    - alert: Detect_FIM_Changed
      expr: sentinel_job_output{changed1=~".+"}
      for: 0m
      labels:
        severity: info
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - Detect_FIM_Changed
        description: "{{ $labels.instance }} of job {{ $labels.job }} Detect_FIM_Changed \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # sentinel_watch_syslog_rule_engine
    - alert: sentinel_watch_syslog_rule_engine
      expr: sentinel_watch_syslog_rule_engine{}
      for: 0m
      labels:
        severity: info
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - sentinel_watch_syslog_rule_engine
        description: "{{ $labels.instance }} of job {{ $labels.job }} sentinel_watch_syslog_rule_engine \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # check-ntp
    - alert: NTP_Check
      expr: sentinel_job_output{sentinel_job="ntp-check"} > 0
      for: 0m
      labels:
        severity: warning
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - NTP_Check
        description: "{{ $labels.instance }} of job {{ $labels.job }} NTP_Check \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # check-macs
    - alert: Detect_MAC_Address
      expr: sentinel_job_output{sentinel_job="macs-check"} == 1
      for: 0m
      labels:
        severity: info
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - Detect_MAC_Address
        description: "{{ $labels.instance }} of job {{ $labels.job }} Detect_MAC_Address \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        



    # sentinel_job_not_done
    - alert: sentinel_job_not_done
      expr: sentinel_job{start=~".+",done=""}
      for: 5m 
      labels:
        severity: warning
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - sentinel_job_not_done
        description: "{{ $labels.instance }} of job {{ $labels.job }} sentinel_job_not_done \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # sentinel_job_no_success
    - alert: sentinel_job_no_success
      expr: sentinel_job{start=~".+",success!="True"}
      for: 5m
      labels:
        severity: warning
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - sentinel_job_no_success
        description: "{{ $labels.instance }} of job {{ $labels.job }} sentinel_job_no_success \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


# sum by (instance) (sentinel_job{}) < 1

    # sentinel_watch_syslog_rule_engine_gt_100
    - alert: sentinel_watch_syslog_rule_engine_gt_100
      expr: count by(instance) (sentinel_watch_syslog_rule_engine{}) > 100
      for: 0m
      labels:
        severity: warning
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - sentinel_watch_syslog_rule_engine_gt_100
        description: "{{ $labels.instance }} of job {{ $labels.job }} sentinel_watch_syslog_rule_engine_gt_100 \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    # sentinel_job_output_gt_100
    - alert: sentinel_job_output_gt_100
      expr: count by(instance) (sentinel_job_output{}) > 100
      for: 0m
      labels:
        severity: warning
        owner: sentinel
      annotations:
        summary: Instance {{ $labels.instance }} - sentinel_job_output_gt_100
        description: "{{ $labels.instance }} of job {{ $labels.job }} sentinel_job_output_gt_100 \n VALUE = {{ $value }}\n  LABELS: {{ $labels }}"




